Регистрация завершена, и к ней написаны тесты на контроллер
Concerts-Mate/Users-Service pull request #18
Opened 2024-04-14 10:59 UTC by llirik42

@dura0ok должен сделать ревью как тимлид, @pipichinka должен сделать ревью как ?????, @Wooshey1411 должен сделать ревью как конечный пользователь (все ли нужные коды ошибок есть, нормально ли то то возвращается и т.д.).

2024-04-14 14:56 UTC, dura0ok requested changes

2024-04-14 14:56 UTC, dura0ok commented on src/main/java/ru/nsu/concertsmate/users_service/model/entities/UserCityEmbeddedEntity.java
> +        @UniqueConstraint(name = "users_cities_pk", columnNames = {"user_id", "city_name"})
то что в двух местах констрэйнт дублируется можно как-то избежать?

2024-04-14 14:56 UTC, dura0ok commented on src/main/resources/application.yaml
> +    username: admin
убери(

2024-04-14 14:56 UTC, dura0ok commented on src/test/resources/application.yaml
> +    username: admin
убери

2024-04-14 15:01 UTC, dura0ok commented on src/main/java/ru/nsu/concertsmate/users_service/model/entities/UserCityEmbeddedEntity.java
> +        @UniqueConstraint(name = "users_cities_pk", columnNames = {"user_id", "city_name"})
при создании таблиц тоже тип

2024-04-15 16:32 UTC, Wooshey1411 commented on src/main/java/ru/nsu/concertsmate/users_service/api/users/UserCitiesResponse.java
> +        this.cities = new ArrayList<>();
В текущем состоянии протокола если не SUCCESS, то действительно, ничего больше сдать не надо кроме заголовка

2024-04-15 16:44 UTC, Wooshey1411 commented on src/main/java/ru/nsu/concertsmate/users_service/api/users/UsersApiResponse.java
Класс называется UsersApiResponse, у нас и так все ответы являются User api response, нужно обозвать по другому, здесь ответ без данных, просто заголовок: как варианты DefaultResponse, OnlyHeaderResponse

2024-04-15 16:46 UTC, Wooshey1411 commented on src/main/java/ru/nsu/concertsmate/users_service/api/users/UsersApiResponseStatus.java
decription отдан на откуп названиям в Enum, при желании можно для каждого кода сделать дефолтный description

2024-04-15 16:46 UTC, dura0ok commented on src/main/java/ru/nsu/concertsmate/users_service/api/users/UsersApiResponse.java
Поддерживаю!

2024-04-15 16:46 UTC, dura0ok commented on src/main/java/ru/nsu/concertsmate/users_service/api/users/UsersApiResponseStatus.java
да, я тоже так сделал

2024-04-15 16:50 UTC, Wooshey1411 commented on src/main/java/ru/nsu/concertsmate/users_service/controllers/UsersController.java
> +    public UserConcertsResponse getUserConcerts(long telegramId) {
Все функции как-то реализованы, кроме этой. Как я понимаю она смотрит только есть ли юзер в DB, но не смотрит концерты, если это так, то нужна заглушка.

2024-04-15 16:52 UTC, dura0ok commented on src/main/java/ru/nsu/concertsmate/users_service/controllers/UsersController.java
> +    public UserConcertsResponse getUserConcerts(long telegramId) {
Поддерживаю!

2024-04-15 16:52 UTC, llirik42 commented on src/main/java/ru/nsu/concertsmate/users_service/controllers/UsersController.java
> +    public UserConcertsResponse getUserConcerts(long telegramId) {
Возвращать просто список каких-то рандомных руками забитых концертов, если пользователь существует?

2024-04-15 16:52 UTC, Wooshey1411 commented on src/main/java/ru/nsu/concertsmate/users_service/model/dto/UserCityDto.java
>      private long userId;
Зачем тут userId ?

2024-04-15 16:52 UTC, llirik42 commented on src/main/java/ru/nsu/concertsmate/users_service/controllers/UsersController.java
> +    public UserConcertsResponse getUserConcerts(long telegramId) {
Пока нет взаимодействия с Music-Service

2024-04-15 16:52 UTC, Wooshey1411 commented on src/main/java/ru/nsu/concertsmate/users_service/model/dto/UserTracksListDto.java
> +    private long userId;
И тут тоже

2024-04-15 16:54 UTC, llirik42 commented on src/main/java/ru/nsu/concertsmate/users_service/model/dto/UserCityDto.java
>      private long userId;
Хз. Наследие от Миши осталось, надо почекать.

2024-04-15 16:54 UTC, llirik42 commented on src/main/java/ru/nsu/concertsmate/users_service/model/dto/UserCityDto.java
>      private long userId;
@pipichinka

2024-04-15 16:54 UTC, Wooshey1411 commented on src/main/java/ru/nsu/concertsmate/users_service/controllers/UsersController.java
> +    public UserConcertsResponse getUserConcerts(long telegramId) {
Можно сделать функцию которая не обращаясь у другим сервисам вернёт хоть что-то. Чтобы не забыть потом, что нужно редактировать это место. А уже допиливать общение с сервисом

2024-04-15 16:56 UTC, Wooshey1411 commented
+ еще нужно согласовать еще пару методов с api: получение любимых исполнителей, которых мы определили и возможность включить/отключить шедулинг для определенного юзера

2024-04-15 16:56 UTC, dura0ok commented on src/main/java/ru/nsu/concertsmate/users_service/model/dto/UserCityDto.java
>      private long userId;
0_0 интересно мы же сразу решили  что **telegram_id - pk**

2024-04-15 17:00 UTC, llirik42 commented
> * еще нужно согласовать еще пару методов с api: получение любимых исполнителей, которых мы определили и возможность включить/отключить шедулинг для определенного юзера

Я если честно не вижу смысла в получении любимых исполнителей, потому что эта информация нигде не хранится и никак изменить её нельзя. Текущий список любимых исполнителей определяется пользовательскими плейлистами и альбомами (вот их список можно менять), а зачем получать текущих исполнителей, если этот список нельзя отдельно поменять ....

2024-04-15 17:00 UTC, llirik42 commented
> * еще нужно согласовать еще пару методов с api: получение любимых исполнителей, которых мы определили и возможность включить/отключить шедулинг для определенного юзера

Давай всё-таки возможность отключения уведомлений будет потом. Как мне кажется, сейчас есть более насущные проблемы. @dura0ok, добавь issue по этому поводу на будущее

2024-04-15 17:01 UTC, Wooshey1411 commented on src/main/java/ru/nsu/concertsmate/users_service/services/exceptions/CityNotAddedException.java
> +public class CityNotAddedException extends Exception {
Нам нужен такой широкий класс исключений, тем более checked? Можно использовать RuntimeException?

2024-04-15 17:03 UTC, Wooshey1411 reviewed
some comment?

2024-04-15 17:21 UTC, llirik42 commented on src/main/java/ru/nsu/concertsmate/users_service/services/exceptions/CityNotAddedException.java
> +public class CityNotAddedException extends Exception {
Нужен

2024-04-15 17:21 UTC, llirik42 commented on src/main/java/ru/nsu/concertsmate/users_service/services/exceptions/CityNotAddedException.java
> +public class CityNotAddedException extends Exception {
Конечно можно, но зачем?

2024-04-15 17:21 UTC, llirik42 commented
> some comment?

Видимо

2024-04-15 17:24 UTC, dura0ok commented
> > * еще нужно согласовать еще пару методов с api: получение любимых исполнителей, которых мы определили и возможность включить/отключить шедулинг для определенного юзера
> 
> Я если честно не вижу смысла в получении любимых исполнителей, потому что эта информация нигде не хранится и никак изменить её нельзя. Текущий список любимых исполнителей определяется пользовательскими плейлистами и альбомами (вот их список можно менять), а зачем получать текущих исполнителей, если этот список нельзя отдельно поменять ....

Мне кажется это спорно, возможно и надо(все равно тебе это для бизнес логики сделать придется, выносить снаружу можно.
Например вдруг твой сервис закэшировал исполнителей пользователя, а он уже обновил
Или мы как-то по принудительной кнопки запроса концертов будем запрашивать без кэша? @llirik42

2024-04-15 17:27 UTC, llirik42 commented
> > > * еще нужно согласовать еще пару методов с api: получение любимых исполнителей, которых мы определили и возможность включить/отключить шедулинг для определенного юзера
> > 
> > 
> > Я если честно не вижу смысла в получении любимых исполнителей, потому что эта информация нигде не хранится и никак изменить её нельзя. Текущий список любимых исполнителей определяется пользовательскими плейлистами и альбомами (вот их список можно менять), а зачем получать текущих исполнителей, если этот список нельзя отдельно поменять ....
> 
> Мне кажется это спорно, возможно и надо(все равно тебе это для бизнес логики сделать придется, выносить снаружу можно. Например вдруг твой сервис закэшировал исполнителей пользователя, а он уже обновил Или мы как-то по принудительной кнопки запроса концертов будем запрашивать без кэша? @llirik42

Я просто не вижу смысла получать исполнителей. Ну получил ты и что? Ты не можешь их удалить или кого-то туда добавить напрямую (лишь добавить/удалить ссылку на плейлист/альбом)

2024-04-15 17:28 UTC, dura0ok commented
> > > > * еще нужно согласовать еще пару методов с api: получение любимых исполнителей, которых мы определили и возможность включить/отключить шедулинг для определенного юзера
> > > 
> > > 
> > > Я если честно не вижу смысла в получении любимых исполнителей, потому что эта информация нигде не хранится и никак изменить её нельзя. Текущий список любимых исполнителей определяется пользовательскими плейлистами и альбомами (вот их список можно менять), а зачем получать текущих исполнителей, если этот список нельзя отдельно поменять ....
> > 
> > 
> > Мне кажется это спорно, возможно и надо(все равно тебе это для бизнес логики сделать придется, выносить снаружу можно. Например вдруг твой сервис закэшировал исполнителей пользователя, а он уже обновил Или мы как-то по принудительной кнопки запроса концертов будем запрашивать без кэша? @llirik42
> 
> Я просто не вижу смысла получать исполнителей. Ну получил ты и что? Ты не можешь их удалить или кого-то туда добавить напрямую (лишь добавить/удалить ссылку на плейлист/альбом)

Ну это да тут согласен)) Это может и сервис музыки показывать по идее?
Если нет, то можно сделать фишкой, а так да
но вот проблему про кэширование надо задуматься

2024-04-16 16:05 UTC, dura0ok approved these changes

2024-04-16 16:07 UTC, dura0ok commented
@pipichinka 
![изображение](https://github.com/Concerts-Mate/Users-Service/assets/28489754/4af7cf53-a18b-47c6-ba61-c0920a006ded)
![изображение](https://github.com/Concerts-Mate/Users-Service/assets/28489754/0865d29c-5b93-45fb-ad37-7f70a3d659aa)

С тебя пофиксить это в след PR

2024-04-16 16:07 UTC, merged