сделал общение с сервисом Кирилла
Concerts-Mate/Users-Service pull request #29
Opened 2024-04-19 06:34 UTC by pipichinka

методы подёргал, вроде работают)

2024-04-19 06:36 UTC, pipichinka commented
смог присоединить только в должок
УВЫ

2024-04-19 06:38 UTC, llirik42 requested changes

2024-04-19 06:38 UTC, llirik42 commented on src/main/java/ru/nsu/concerts_mate/users_service/model/dto/ArtistDto.java
> +    private int yandex_music_id;
Это бан. Сделай нормально: все поля в стил Java называются, но просто сериализуются и десериализуются они из/в поля с другими названиями (это через аннотации делается)

2024-04-19 06:38 UTC, llirik42 commented on src/main/java/ru/nsu/concerts_mate/users_service/model/dto/ConcertDto.java
> +    private String afisha_url;
бан

2024-04-19 06:38 UTC, llirik42 commented on src/main/java/ru/nsu/concerts_mate/users_service/model/dto/ConcertDto.java
> +    private String map_url;
бан

2024-04-19 06:38 UTC, llirik42 commented on src/main/java/ru/nsu/concerts_mate/users_service/model/dto/ConcertDto.java
> +    private PriceDto min_price;
бан

2024-04-19 06:38 UTC, llirik42 commented on src/main/java/ru/nsu/concerts_mate/users_service/services/exceptions/MusicServiceException.java
> +public class MusicServiceException extends Exception{
Брат, используй автоформатирование. Клянусь, код станет красивее

2024-04-19 06:38 UTC, llirik42 commented on src/main/java/ru/nsu/concerts_mate/users_service/services/impl/MusicServiceImpl.java
> +            if (res.getStatusCode().value() == 422 || !res.hasBody()){
Отбей код 422

2024-04-19 06:40 UTC, pipichinka commented on src/main/java/ru/nsu/concerts_mate/users_service/model/dto/ArtistDto.java
> +    private int yandex_music_id;
какие блять?

2024-04-19 06:41 UTC, pipichinka commented on src/main/java/ru/nsu/concerts_mate/users_service/services/impl/MusicServiceImpl.java
> +            if (res.getStatusCode().value() == 422 || !res.hasBody()){
что?

2024-04-19 06:41 UTC, llirik42 commented on src/main/java/ru/nsu/concerts_mate/users_service/model/dto/ArtistDto.java
> +    private int yandex_music_id;
Кто какие

2024-04-19 06:42 UTC, llirik42 commented on src/main/java/ru/nsu/concerts_mate/users_service/services/impl/MusicServiceImpl.java
> +            if (res.getStatusCode().value() == 422 || !res.hasBody()){
То

2024-04-19 06:42 UTC, pipichinka commented on src/main/java/ru/nsu/concerts_mate/users_service/services/impl/MusicServiceImpl.java
> +            if (res.getStatusCode().value() == 422 || !res.hasBody()){
что значит отбей

2024-04-19 06:42 UTC, dura0ok commented on src/main/java/ru/nsu/concerts_mate/users_service/model/dto/ArtistDto.java
> +    private int yandex_music_id;
Гойда

2024-04-19 06:43 UTC, dura0ok commented on src/main/java/ru/nsu/concerts_mate/users_service/services/exceptions/MusicServiceException.java
> +public class MusicServiceException extends Exception{
Гойда

2024-04-19 06:43 UTC, llirik42 commented on src/main/java/ru/nsu/concerts_mate/users_service/model/dto/ArtistDto.java
> +    private int yandex_music_id;
> аннотации

Ну найди, разберись

2024-04-19 06:43 UTC, pipichinka commented on src/main/java/ru/nsu/concerts_mate/users_service/model/dto/ArtistDto.java
> +    private int yandex_music_id;
> Гойда

ГОЙДА ГОЙДА ГОЙДА
ГОЙДА ГОЙДА ГОЙДА
ГОЙДА
ГОЙДА
ГОЙДА
ГОЙДА
ГОЙДА
ГОЙДА
ГОЙДА
ГОЙДА

ГОЙДА ГОЙДА ГОЙДА
ГОЙДА ГОЙДА ГОЙДА
ГОЙДА                ГОЙДА
ГОЙДА                ГОЙДА
ГОЙДА                ГОЙДА
ГОЙДА                ГОЙДА
ГОЙДА ГОЙДА ГОЙДА
ГОЙДА ГОЙДА ГОЙДА

               ГОЙДА

ГОЙДА                ГОЙДА
ГОЙДА                ГОЙДА
ГОЙДА               ГОЙДА! 
ГОЙДА              ГОЙДА!! 
ГОЙДА            ГОЙДА!!!! 
ГОЙДА          ГОЙДА!!!!!! 
ГОЙДА ГОЙДА ГОЙДА
ГОЙДА ГОЙДА ГОЙДА

   ГОЙДА ГОЙДА ГОЙДА
   ГОЙДА ГОЙДА ГОЙДА
   ГОЙДА                ГОЙДА
   ГОЙДА                ГОЙДА
   ГОЙДА                ГОЙДА
   ГОЙДА                ГОЙДА
   ГОЙДА                ГОЙДА
ГОЙДА!!! ГОЙДА!!! ГОЙДА!!!
ГОЙДА!!! ГОЙДА!!! ГОЙДА!!! 
ГОЙДА                          ГОЙДА
ГОЙДА                          ГОЙДА

     ГОЙДА ГОЙДА ГОЙДА
    ГОЙДА ГОЙДА!!ГОЙДА
   ГОЙДА                  ГОЙДА
  ГОЙДА                   ГОЙДА
ГОЙДА!! ГОЙДА!! ГОЙДА
ГОЙДА!! ГОЙДА!!! ГОЙДА
ГОЙДА                      ГОЙДА
ГОЙДА                      ГОЙДА
ГОЙДА                      ГОЙДА
ГОЙДА                      ГОЙДА

2024-04-19 06:43 UTC, dura0ok commented on src/main/java/ru/nsu/concerts_mate/users_service/services/impl/MusicServiceImpl.java
> +            if (res.getStatusCode().value() == 422 || !res.hasBody()){
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpStatus.html&ved=2ahUKEwiunZa71s2FAxWKJxAIHTtlAOUQFnoECBIQAQ&usg=AOvVaw32HRKLvUQnR573lz5POIY1
Гойда

2024-04-19 06:44 UTC, dura0ok commented on src/main/java/ru/nsu/concerts_mate/users_service/services/impl/MusicServiceImpl.java
> +            if (res.getStatusCode().value() == 422 || !res.hasBody()){
https://stackabuse.com/how-to-return-http-status-codes-in-a-spring-boot-application/ ой вот

2024-04-20 14:36 UTC, llirik42 approved these changes
В падлу щас разбираться. Миша скинул теоркод, поэтому всё одобрено

2024-04-20 14:49 UTC, merged